server:
  port: 8081
spring:
  application:
    name: lagou-service-code
  datasource:
    driver-class-name: ${public-datasource.driver-class-name}
    url: ${public-datasource.url}
    username: ${public-datasource.username}
    password: ${public-datasource.password}
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/lagou?serverTimezone=UTC
#    username: root
#    password: root
  jpa:
    database: MySQL
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl  #避免将驼峰命名转换为下划线命名
#注册到Eureka服务中心
eureka:
  client:
    service-url:
      # 注册到集群，就把多个Eurekaserver地址使用逗号连接起来即可；注册到单实例（非集群模式），那就写一个就ok
      defaultZone: http://LagouEurekaServerA:8090/eureka,http://LagouEurekaServerB:8091/eureka
  instance:
    prefer-ip-address: true  #服务实例中显示ip，而不是显示主机名（兼容老的eureka版本）
    # 实例名称： 192.168.1.103:lagou-service-resume:8080，我们可以自定义它
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@
management:
  endpoints:
    web:
      exposure:
        include: "*"